apiVersion: v1
kind: Service
metadata:
  name: gilz-service
  namespace: gilz
spec:
  selector:
    app: gilz-app
  ports:
    - protocol: TCP
      port: 5000          # The port on which the service is exposed inside the cluster
      targetPort: 5000   # The port on the container the application listens on
      nodePort: 30080    # The external port exposed on your desktop's IP
  type: NodePort
